### ISSUE TITLE
2019c is missing

### ISSUE THREAD

**Issue by Haroenv** [rxaviers/iana-tz-data#6]
Can be copied from here? https://github.com/moment/moment-timezone/commit/7ccc3ccce1e696e5b680c19648c5c7cb88447d36

**Comment by rxaviers** [comment]
Thank you for submitting this issue. I've updated this repo up to 2019c.

A small change is needed on top of vanilla moment-timezone data, i.e., https://github.com/rxaviers/moment-timezone/commit/95c69d7dd4066ddf3e6ba139f9141c035781f26f to explicitly include isDST information from IANA
